theme = 'streamingCenter'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
enableRobotsTXT = true

[markup.goldmark.renderer]
unsafe= true

[sitemap]
  changeFreq = 'weekly'
  disable = false
  filename = 'sitemap.xml'
  priority = -1

[caches]
    [caches.getjson]
        dir = ":cacheDir/:project"
        maxAge = "5m"

[languages]
  [languages.ru]
    baseURL = 'https://radio-tochka.com/'
    contentDir = 'content/ru'
    disabled = false
    languageCode = 'ru-RU'
    languageDirection = 'ltr'
    languageName = 'Russian'
    title = 'Radio-Tochka.com'
    weight = 2
    [languages.ru.params]
      subtitle = 'Платформа Интернет-Радио'

    [languages.ru.menus]
      [[languages.ru.menus.main]]
        name = 'Главная'
        pageRef = '/'
        weight = 10
      [[languages.ru.menus.main]]
        name = 'Обзор'
        pageRef = '/tour'
        weight = 20
      [[languages.ru.menus.main]]
        name = 'Цены'
        pageRef = '/pricing'
        weight = 30
      [[languages.ru.menus.main]]
        name = 'Инфо'
        pageRef = '/docs'
        weight = 40
      [[languages.ru.menus.main]]
        name = 'Вход'
        pageRef = 'https://app.radio-tochka.com/login'
        weight = 50

      [[languages.ru.menus.agreement]]
        name = 'Оферта'
        pageRef = '#agreement'
        weight = 10
      [[languages.ru.menus.agreement]]
        name = 'Термины и определения'
        pageRef = '#terms'
        weight = 20

      [[languages.ru.menus.agreement]]
        name = 'Предмет договора'
        pageRef = '#subject'
        weight = 30

      [[languages.ru.menus.agreement]]
        name = 'Права и обязанности сторон'
        pageRef = '#rights'
        weight = 40

      [[languages.ru.menus.agreement]]
        name = 'Порядок оплаты'
        pageRef = '#billing'
        weight = 50
      [[languages.ru.menus.agreement]]
        name = 'Персональные данные, конфиденциальность'
        pageRef = '#privacy'
        weight = 60

      [[languages.ru.menus.agreement]]
        name = 'Реквизиты'
        pageRef = '#requisites'
        weight = 100

        

  [languages.en]
    baseURL = 'https://streaming.center/'
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Streaming.center'
    weight = 1
    [languages.en.params]
      subtitle = 'Internet-radio streaming platform'

    [languages.en.menus]
      [[languages.en.menus.main]]
        name = 'Home'
        pageRef = '/'
        weight = 10
      [[languages.en.menus.main]]
        name = 'Tour'
        pageRef = '/tour'
        weight = 20
      [[languages.en.menus.main]]
        name = 'Price'
        pageRef = '/pricing'
        weight = 30
      [[languages.en.menus.main]]
        name = 'Docs'
        pageRef = '/docs'
        weight = 40
      [[languages.en.menus.main]]
        name = 'Sign In'
        pageRef = 'https://app.streaming.center/login'
        weight = 50

      [[languages.en.menus.agreement]]
        name = 'Agreement'
        pageRef = '#tos'
        weight = 10
      [[languages.en.menus.agreement]]
        name = 'Terms'
        pageRef = '#terms'
        weight = 20
      [[languages.en.menus.agreement]]
        name = 'Billing and Payment'
        pageRef = '#billing'
        weight = 30
      [[languages.en.menus.agreement]]
        name = 'Privacy policy'
        pageRef = '#privacy'
        weight = 40
      [[languages.en.menus.agreement]]
        name = 'Requisites'
        pageRef = '#requisites'
        weight = 100





[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'catppuccin-mocha'
    tabWidth = 4