theme = 'streamingCenter'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
enableRobotsTXT = true

[sitemap]
  changeFreq = 'weekly'
  disable = false
  filename = 'sitemap.xml'
  priority = -1

[languages]
  [languages.ru]
    baseURL = 'https://radio-tochka.com/'
    contentDir = 'content/ru'
    disabled = false
    languageCode = 'ru-RU'
    languageDirection = 'ltr'
    languageName = 'Russian'
    title = 'Radio-Tochka.com'
    weight = 2
    [languages.ru.params]
      subtitle = 'Платформа Интернет-Радио'
      
    [languages.ru.menus]
      [[languages.ru.menus.main]]
        name = 'Главная'
        pageRef = '/'
        weight = 10
      [[languages.ru.menus.main]]
        name = 'Обзор'
        pageRef = '/tour'
        weight = 20
      [[languages.ru.menus.main]]
        name = 'Цены'
        pageRef = '/pricing'
        weight = 30
      [[languages.ru.menus.main]]
        name = 'Инфо'
        pageRef = '/documentation'
        weight = 40
      [[languages.ru.menus.main]]
        name = 'Вход'
        pageRef = 'https://app.radio-tochka.com/login'
        weight = 50

  [languages.en]
    baseURL = 'https://streaming.center/'
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Streaming.center'
    weight = 1
    [languages.en.params]
      subtitle = 'Internet-radio streaming platform'

    [languages.en.menus]
      [[languages.en.menus.main]]
        name = 'Home'
        pageRef = '/'
        weight = 10
      [[languages.en.menus.main]]
        name = 'Tour'
        pageRef = '/tour'
        weight = 20
      [[languages.en.menus.main]]
        name = 'Price'
        pageRef = '/pricing'
        weight = 30
      [[languages.en.menus.main]]
        name = 'Docs'
        pageRef = '/documentation'
        weight = 40
      [[languages.en.menus.main]]
        name = 'Sign In'
        pageRef = 'https://app.radio-tochka.com/login'
        weight = 50